[package]
name = "embeddedpy"
version = "0.1.0"
authors = ["Ciaran McNally <mak@redbrick.dcu.ie>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name="embed"
crate-type=[ "dylib" ]
